.\" manpage for PLACEHOLDER_TITLE
.TH "PLACEHOLDER_NAME" "1" "November 2024" "PLACEHOLDER_TITLE 2024.10.31" "PLACEHOLDER_TITLE Manual"

.SH NAME
PLACEHOLDER_NAME \- PLACEHOLDER_TITLE

.SH SYNOPSIS
\fBPLACEHOLDER_NAME [OPTIONS]\fR

.SH DESCRIPTION
PLACEHOLDER_TITLE is DESCRIPTION.

.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR \fI<path>\fR
Path to the configuration file.

.TP
\fB\-\-override\-validation\fR
Show all available entries, disregarding compatibility checks (\fBUNSAFE\fR).

.TP
\fB\-\-size\-bypass\fR
Bypass the terminal size limit.

.TP
\fB\-y\fR, \fB\-\-skip\-confirmation\fR
Skip confirmation prompt before executing commands.

.TP
\fB\-t\fR, \fB\-\-theme\fR \fI<theme>\fR
Set the theme to use in the TUI.
.br
Possible values:
\fIdefault\fR,
\fIcompatible\fR.
.br
Defaults to \fIdefault\fR.

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help.

.SH AUTHOR
Written by David Vogel.
<david@davidvogel.xyz>

.SH REPORTING BUGS
Since the project is still in active development, you may encounter some issues.
.br

.SH COPYRIGHT
Copyright (c) 2025 David Vogel.
.br
MIT License.
https://opensource.org/license/MIT
